### PR TITLE
fix: load the version and code from git

### PR DESCRIPTION
**Pull request by Avinash-Bhat**
for issue #64

### CODE REVIEW

**Comment by mrmaffen** [comment]
Thanks man! I've merged your commit after tweaking a few things

**Comment by amitbd1508** [comment]
oiyyihhgoollkltttrttttatttttrttts

**Comment by amitbd1508** [comment]
Hi tomahawk-player/toma,

I'd like to add you to my professional network on LinkedIn.

- Amit

Confirm that you know Amit: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Rq_lhUdG&invitationId=6178626873950560256&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eisqdm7ie%7Eb7








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-isqdm7ie-b7&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH5KAZBM8ZkmAAAAVb7l_PnOcpIYgUrYBMo9hxRpCrkmcySN8-UrYgkp9WXiQpSHIAZdzwwBXsaKmo6r7ZQkWWEqRR_KuJMKBjrNZNtQcB5_vs3Sy3VWIRRrQlJPf9ezisIXtfjtIIAw0YfpzVWTLKFZlDVN4OACIk-JxCIDF5V3uZFohSTIcZ7iwllaF1FyyUS&eid=0-isqdm7ie-b7


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-isqdm7ie-b7&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amitbd1508** [comment]
Amit Ghosh would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Rq_lhUdG&invitationId=6178626873950560256&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-r5km72%7Eit0qmuqq%7Ew7

View Amit Ghosh&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Rq_lhUdG&invitationId=6178626873950560256&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-r5km72%7Eit0qmuqq%7Ew7





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=r5km72-it0qmuqq-w7&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=r5km72-it0qmuqq-w7&loid=AQF2Gb7h7Xo_ZgAAAVciIhZEtIqFnnI-IlC0u8eTjy5V3edPToHFWH8fk8hNlaK94QKVTl44hOaH4TaQGAxgqnIiDYe1-Ih_MzLpMcGkVRWm-TBlQMjXpWR_gDHa6o6WWgSXDbOHUOCywl-i0nlouB-PcqZgJcdOzgMqEuB44aen40iEynEBcwMZk0DWfohsT-qX

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=r5km72-it0qmuqq-w7&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by amitbd1508** [comment]
Hi ,

Amit Ghosh would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Rq_lhUdG&invitationId=6178626873950560256&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-r5km72%7Eitaqoslr%7Ecy

View Amit Ghosh&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Rq_lhUdG&invitationId=6178626873950560256&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-r5km72%7Eitaqoslr%7Ecy





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=r5km72-itaqoslr-cy&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=r5km72-itaqoslr-cy&loid=AQE5ip7jcPvBmgAAAVdHGCcwKAS1n1mopDL7VL9PV-nrChlsOJNSIIT3VO8c4Q8V0g7xcKxsOZSzJ-JmAis1NTNNR-MWvPCHglKBAvjwLJ8JLW89fHO1aW7kzLv_zQssERXi796iU63BqpBBMcx9TuuCkh2vz5CTquWY1XJzw285jKwitV6gamcekpTNaQPQ65ii

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=r5km72-itaqoslr-cy&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by muesli** [comment]
@amitbd1508 Please stop spamming our bug trackers with your invites.

**Comment by Avinash-Bhat** [comment]
@muesli please [report](https://github.com/contact/report-abuse?report=amitbd1508) the guy

**Pull request closed without merging**
