### PR TITLE
Fix plurals

### PR DESCRIPTION
**Pull request by SafaAlfulaij**
A first attempt to fix plural strings in the app :)
Should return the missing contexts that I removed.

(Not tested at all!)

### CODE REVIEW

**Comment by SafaAlfulaij** [comment]
@mrmaffen Ping?

**Comment by rockymontana** [comment]
The translations shouldn't be hard coded like that but (probably) come from a translation file and be pluralized properly (or via a translation tool).
For instance - in the Swedish language pluralization isn't just adding an s on strings, which would make a commit like this break the i18n of the app is set to be Swedish.

**Comment by rockymontana** [comment]
Sorry... Missed the concept of the changes.
My point is still valid though :-)

**Comment by SafaAlfulaij** [comment]
This isn't a translation but implementing the plural strings in the app itself so that we can use them in the translations. (http://developer.android.com/guide/topics/resources/string-resource.html#Plurals)

I'm really beginner (Under zero) in Java and I just followed what I've seen in the Android docs :)

**Comment by SafaAlfulaij** [comment]
Thanks a lot! :+1: +

**Pull request merged**
